#model_config_test.yaml
model_paths:
  HorseRaceDataSet_path: ./data_cache/tiny_multi_task.pkl
  optimization_output_path: ./model_eval_cache/model_eval_test
model_options:
  X_cat_names: ["task_attr"]
  y_name: "score"
  model_type: "ElasticNet"
  inversely_weight_tasks: True
optimization_options:
  n_iterations: 100
  total_trials: 6